name: Auto Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/wisata-wringinsongo/
            sudo git pull
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader
            sudo php artisan migrate:fresh --seed
            sudo php artisan optimize
            sudo php artisan cache:clear
            sudo php artisan route:clear
            sudo php artisan view:clear
            sudo php artisan config:cache